version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    # If your application needs environment variables:
    # environment:
    #   - SPRING_PROFILES_ACTIVE=production
    #   - DATABASE_URL=...